# Generated by Django 2.2.6 on 2019-12-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrownEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grown_by', models.CharField(max_length=42)),
                ('plant_id', models.PositiveIntegerField()),
                ('seed', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TransferEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(max_length=42)),
                ('to_address', models.CharField(max_length=42)),
                ('plant_id', models.PositiveIntegerField()),
                ('block_number', models.PositiveIntegerField()),
            ],
        ),
    ]
