# Generated by Django 2.2.6 on 2019-12-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20191205_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockHeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_height', models.CharField(max_length=78)),
                ('time', models.DateTimeField()),
                ('block_hash', models.CharField(max_length=66)),
            ],
        ),
    ]
