# Generated by Django 2.2.6 on 2020-01-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_blockchecksingleton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchecksingleton',
            name='highest_block_checked',
            field=models.CharField(default='0', max_length=78),
        ),
    ]
