# Generated by Django 2.2.6 on 2019-12-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='greens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
