# Generated by Django 2.2.6 on 2019-12-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='last_green_calc',
            field=models.CharField(max_length=78),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plantTime',
            field=models.CharField(max_length=78),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_id',
            field=models.CharField(max_length=78, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='seed',
            field=models.CharField(default='', max_length=78),
        ),
        migrations.AlterField(
            model_name='plant',
            name='value',
            field=models.CharField(max_length=78),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['owner'], name='plants_plan_owner_1ff0c9_idx'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['erc20_address'], name='plants_plan_erc20_a_737277_idx'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['plant_id'], name='plants_plan_plant_i_677a5a_idx'),
        ),
    ]
