# Generated by Django 2.2.6 on 2019-12-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_plant_greens_per_block'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='plantTime',
            new_name='plant_time',
        ),
    ]
