# Generated by Django 2.2.6 on 2019-12-10 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbadge',
            name='badge_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='badges.Badge'),
        ),
    ]
